### ISSUE TITLE
paralel edges - check fails

### ISSUE THREAD

**Issue by zeffii** [zeffii/mesh_tinyCAD#45]
thanks to lijenstina on irc  freenode  `blenderpython` for pointing it out.

```python
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\mesh_tinyCAD\VTX.py", line 148, in execute
    if checkVTX(self, context):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\mesh_tinyCAD\VTX.py", line 59, in checkVTX
    getVTX(self)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\mesh_tinyCAD\VTX.py", line 15, in getVTX
    self.point = cm.get_intersection(self.edge1, self.edge2)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\mesh_tinyCAD\cad_module.py", line 41, in get_intersection
    return ((line[0] + line[1]) / 2)
TypeError: 'NoneType' object is not subscriptable

```

`intersect_line_line`  :   Takes 2 segments (defined by 4 vectors) and returns a vector for their point of intersection or None.

in the case of non intersecting lines this should return None, hence the error.

**Comment by zeffii** [comment]
i've added code to prevent this from happening. Thinks it's resolved now, but more testing is always welcome.
